#    Copyright (C) 2005 Ruben Moreno Montoliu <ruben3d@gmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

################################################################################
#                                                                              #
# Makefile.config                                                              #
#                                                                              #
# User configurable parameters for the building proccess.                      #
#                                                                              #
################################################################################


################################################################################

# Project directory structure

################################################################################

# Base directory of the project (all the relative paths are concatenated with
# this path).
PROJECT_PATH=$(shell pwd)/../../..

# Directory where final binary files are placed.
BIN_PATH=bin/cpp

# Directory where temporary object files and dependencies are stored.
BUILD_PATH=build/cpp

# Directory with the source code.
SRC_PATH=src/cpp

# Directory where the documentation is generated and stored.
DOC_PATH=doc/cpp

# Directory where the distribution is generated.
DIST_PATH=dist

# In this directory all the data used by the application is stored. The 'bin'
# target uses this directory as workpath and all its contents are copied into
# the basedir of the distribution.
DATA_PATH=data

INSTALL_PATH=install


################################################################################

# File names

################################################################################

# Name of the final executable file.
TARGET=concentrator

# Name of the Doxygen configuration file.
DOXYFILE=Doxyfile

# Name of the compressed file where the distribution is stored (.tar.gz is
# automatically appended).
DISTFILE=dist_`date +%Y%m%d_%H%M`


################################################################################

# Additional resources

################################################################################

# Additional source directories under SRC_PATH.
SRC_SUBDIRS=data

EXCLUDE=ssl/win.c

# Additional libraries to be linked.
LIBS=crypt

# Additional static libraries to be linked
STATICS=$(PROJECT_PATH)/lib/cpp/opengate5.x/$(ARCH_PREFIX)/$(PROFILE_PREFIX)/libogapi.a \
        $(PROJECT_PATH)/lib/c/neomediaRMR/i686/librmr.a

# Path for additional includes (header files not included into a source
# directory).
INC=$(addsuffix /hdrs, $(SRC_SUBDIRS)) ./hdrs ../../lib/cpp/opengate5.x/hdrs

# Additional paths with Makefiles to be executed.
MAKEFILE_PATHS=


################################################################################

# Generation options

################################################################################

# Builds an static library instead of an executable binay.
GENERATE_STATIC_LIBRARY=no

# Removes all the symbol information from the binary.
STRIP_TARGET=yes

# Name of the doxygen application (in order to generate documentation).
DOXYGEN=doxygen
